//
//  TimestampUnwrapVectorsTest.swift
//  ShimmerBluetoothTests
//
//  Created by Shimmer Engineering on 17/09/2026.
//

import XCTest
@testable import ShimmerBluetooth

/// The timestamp-unwrap rule, run against the vectors every Shimmer host API is
/// checked against.
///
/// The set is specified and generated in the firmware repository -
/// `log-and-stream-common`, `Test/conformance/timestamp_unwrap.json`, beside the
/// prose it encodes and a reference implementation that regenerates and
/// re-checks it in CI. The Java, C#, Python and TypeScript APIs load that file
/// directly; a classic Xcode project would need four hand-edited entries in
/// project.pbxproj to carry a resource nothing compiles, so this target gets the
/// same vectors as generated source instead:
///
///     python Test/host/crosscheck_timestamp_unwrap.py --emit swift
///
/// Why go to that trouble for what looks like arithmetic: five implementations
/// of one wire format drifted apart once already, and the same unwrap defect sat
/// in all five for years - each reviewed on its own, against prose, by people
/// who had no way to run the others. A shared set turns "these should agree"
/// into something a suite fails on.

/// One vector: a raw counter sequence and what every host must make of it.
struct UnwrapVector {
    let id: String
    let modulo: Int
    let reorderWindowTicks: Double
    let raw: [Double]
    let expectedUnwrapped: [Double]
    let expectedRejected: [Bool]
    let expectedFinalCycle: Int
}

/// One window derivation: a sampling rate and the window it must produce.
struct WindowDerivationCase {
    let samplingRateHz: Double?
    let timestampBits: Int
    let expectedReorderWindowTicks: Double
    let tolerance: Double
}

// Generated by Test/host/crosscheck_timestamp_unwrap.py --emit swift
// Source: Test/conformance/timestamp_unwrap.json revision 1
// Do not hand-edit; regenerate when the vector file changes.

let sharedVectorRevision = 1
let sharedTicksPerSecond = 32768
let sharedInvalidZeroWindowTicks = 32768
let sharedReorderPeriods = 8
let sharedMaxWindowDivisor = 8

let sharedUnwrapVectors: [UnwrapVector] = [
    UnwrapVector(
        id: "monotonic-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [1000, 1065, 1130],
        expectedUnwrapped: [1000, 1065, 1130],
        expectedRejected: [false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "wrap-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16777200, 16],
        expectedUnwrapped: [16777200, 16777232],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "wrap-lands-on-zero-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16777116, 0],
        expectedUnwrapped: [16777116, 16777216],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "invalid-zero-signature-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [7406116, 7406506, 0, 7406571],
        expectedUnwrapped: [7406116, 7406506, 7406506, 7406571],
        expectedRejected: [false, false, true, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "invalid-zero-no-cascade-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [7406506, 0, 7406571, 7406636],
        expectedUnwrapped: [7406506, 7406506, 7406571, 7406636],
        expectedRejected: [false, true, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "first-sample-zero-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [0, 65, 130],
        expectedUnwrapped: [0, 65, 130],
        expectedRejected: [false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "wrap-16bit",
        modulo: 65536,
        reorderWindowTicks: 5120.0,
        raw: [65436, 28],
        expectedUnwrapped: [65436, 65564],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "zero-on-16bit-is-a-wrap",
        modulo: 65536,
        reorderWindowTicks: 5120.0,
        raw: [30000, 0],
        expectedUnwrapped: [30000, 65536],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "backward-step-outside-window-is-a-wrap-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [7406506, 1],
        expectedUnwrapped: [7406506, 16777217],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "duplicate-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [1000, 1065, 1065, 1130],
        expectedUnwrapped: [1000, 1065, 1065, 1130],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "reorder-one-period-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [1000, 1130, 1065, 1195],
        expectedUnwrapped: [1000, 1130, 1065, 1195],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "reorder-one-period-16bit",
        modulo: 65536,
        reorderWindowTicks: 5120.0,
        raw: [40000, 41280, 40640, 41920],
        expectedUnwrapped: [40000, 41280, 40640, 41920],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "reorder-across-wrap-boundary-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16777206, 5, 16777206, 70],
        expectedUnwrapped: [16777206, 16777221, 16777206, 16777286],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "wrap-after-heavy-loss-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16000000, 100],
        expectedUnwrapped: [16000000, 16777316],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "wrap-after-heavy-loss-16bit",
        modulo: 65536,
        reorderWindowTicks: 5120.0,
        raw: [60000, 1000],
        expectedUnwrapped: [60000, 66536],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "wrap-spanning-dropout-1p8s-16bit",
        modulo: 65536,
        reorderWindowTicks: 5120.0,
        raw: [60000, 53446],
        expectedUnwrapped: [60000, 118982],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "wrap-spanning-dropout-152s-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16000000, 4222784],
        expectedUnwrapped: [16000000, 21000000],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "rate-unknown-backward-step-is-a-wrap-24bit",
        modulo: 16777216,
        reorderWindowTicks: 0.0,
        raw: [1000, 1130, 1065, 1195],
        expectedUnwrapped: [1000, 1130, 16778281, 16778411],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "rate-unknown-zero-still-rejected-24bit",
        modulo: 16777216,
        reorderWindowTicks: 0.0,
        raw: [7406506, 0, 7406571],
        expectedUnwrapped: [7406506, 7406506, 7406571],
        expectedRejected: [false, true, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "zero-within-window-of-origin-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [300, 365, 0, 430],
        expectedUnwrapped: [300, 365, 0, 430],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "zero-within-window-after-wrap-24bit",
        modulo: 16777216,
        reorderWindowTicks: 520.0,
        raw: [16777100, 100, 165, 0, 230],
        expectedUnwrapped: [16777100, 16777316, 16777381, 16777216, 16777446],
        expectedRejected: [false, false, false, false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "reorder-window-boundary-inclusive-24bit",
        modulo: 16777216,
        reorderWindowTicks: 512.0,
        raw: [10512, 10000],
        expectedUnwrapped: [10512, 10000],
        expectedRejected: [false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "reorder-window-boundary-exclusive-24bit",
        modulo: 16777216,
        reorderWindowTicks: 512.0,
        raw: [10513, 10000],
        expectedUnwrapped: [10513, 16787216],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "low-rate-clamp-16bit",
        modulo: 65536,
        reorderWindowTicks: 8192.0,
        raw: [60000, 1000],
        expectedUnwrapped: [60000, 66536],
        expectedRejected: [false, false],
        expectedFinalCycle: 1),
    UnwrapVector(
        id: "high-rate-reorder-24bit",
        modulo: 16777216,
        reorderWindowTicks: 256.0,
        raw: [5000, 5032, 5000, 5064],
        expectedUnwrapped: [5000, 5032, 5000, 5064],
        expectedRejected: [false, false, false, false],
        expectedFinalCycle: 0),
    UnwrapVector(
        id: "reorder-beyond-eight-periods-is-a-wrap-24bit",
        modulo: 16777216,
        reorderWindowTicks: 256.0,
        raw: [5000, 5288, 5000],
        expectedUnwrapped: [5000, 5288, 16782216],
        expectedRejected: [false, false, false],
        expectedFinalCycle: 1),
]

let sharedWindowDerivationCases: [WindowDerivationCase] = [
    WindowDerivationCase(
        samplingRateHz: 504.12307692307695,
        timestampBits: 24,
        expectedReorderWindowTicks: 520.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 51.2,
        timestampBits: 16,
        expectedReorderWindowTicks: 5120.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 51.2,
        timestampBits: 24,
        expectedReorderWindowTicks: 5120.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 512.0,
        timestampBits: 24,
        expectedReorderWindowTicks: 512.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 1024.0,
        timestampBits: 24,
        expectedReorderWindowTicks: 256.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 1.0,
        timestampBits: 16,
        expectedReorderWindowTicks: 8192.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 1.0,
        timestampBits: 24,
        expectedReorderWindowTicks: 262144.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 0.0,
        timestampBits: 24,
        expectedReorderWindowTicks: 0.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: nil,
        timestampBits: 24,
        expectedReorderWindowTicks: 0.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: -5.0,
        timestampBits: 24,
        expectedReorderWindowTicks: 0.0,
        tolerance: 0.0),
    WindowDerivationCase(
        samplingRateHz: 512.2950819672132,
        timestampBits: 24,
        expectedReorderWindowTicks: 511.705088,
        tolerance: 0.0001),
]

final class TimestampUnwrapVectorsTest: XCTestCase {

    /// A bumped revision means the rule moved. Read the upstream change before
    /// touching anything here.
    func testRevisionIsTheOneThisSuiteWasWrittenAgainst() {
        XCTAssertEqual(sharedVectorRevision, 1)
        XCTAssertEqual(sharedTicksPerSecond, Int(TimestampUnwrap.rtcTicksPerSecond))
        XCTAssertEqual(sharedInvalidZeroWindowTicks, TimestampUnwrap.wrapWindowTicks)
        XCTAssertEqual(sharedReorderPeriods, TimestampUnwrap.reorderPeriods)
        XCTAssertEqual(sharedMaxWindowDivisor, TimestampUnwrap.maxWindowDivisor)
    }

    /// A vector that stops being run is a vector that stops protecting
    /// anything, and a loop over whatever the array happens to hold would not
    /// notice. Updating this list is the moment to ask what changed upstream.
    func testVectorSetIsComplete() {
        let expectedIds = [
        "monotonic-24bit",
        "wrap-24bit",
        "wrap-lands-on-zero-24bit",
        "invalid-zero-signature-24bit",
        "invalid-zero-no-cascade-24bit",
        "first-sample-zero-24bit",
        "wrap-16bit",
        "zero-on-16bit-is-a-wrap",
        "backward-step-outside-window-is-a-wrap-24bit",
        "duplicate-24bit",
        "reorder-one-period-24bit",
        "reorder-one-period-16bit",
        "reorder-across-wrap-boundary-24bit",
        "wrap-after-heavy-loss-24bit",
        "wrap-after-heavy-loss-16bit",
        "wrap-spanning-dropout-1p8s-16bit",
        "wrap-spanning-dropout-152s-24bit",
        "rate-unknown-backward-step-is-a-wrap-24bit",
        "rate-unknown-zero-still-rejected-24bit",
        "zero-within-window-of-origin-24bit",
        "zero-within-window-after-wrap-24bit",
        "reorder-window-boundary-inclusive-24bit",
        "reorder-window-boundary-exclusive-24bit",
        "low-rate-clamp-16bit",
        "high-rate-reorder-24bit",
        "reorder-beyond-eight-periods-is-a-wrap-24bit"
        ]
        XCTAssertEqual(sharedUnwrapVectors.map { $0.id }, expectedIds)
        XCTAssertEqual(sharedWindowDerivationCases.count, 11)
    }

    func testAllSharedVectorsAgree() {
        for vector in sharedUnwrapVectors {
            var lastUnwrapped = 0.0
            var cycle = 0.0

            for (i, raw) in vector.raw.enumerated() {
                let result = TimestampUnwrap.unwrap(rawTicks: raw,
                                                    lastUnwrapped: lastUnwrapped,
                                                    cycle: cycle,
                                                    maxTicks: vector.modulo,
                                                    reorderWindowTicks: vector.reorderWindowTicks)
                XCTAssertEqual(result.unwrappedTicks, vector.expectedUnwrapped[i], accuracy: 0.0,
                               "\(vector.id): sample \(i)")
                XCTAssertEqual(result.rejected, vector.expectedRejected[i],
                               "\(vector.id): sample \(i) rejected")
                lastUnwrapped = result.unwrappedTicks
                cycle = result.cycle
            }

            XCTAssertEqual(cycle, Double(vector.expectedFinalCycle), accuracy: 0.0,
                           "\(vector.id): final cycle")
        }
    }

    func testWindowDerivationCases() {
        for testCase in sharedWindowDerivationCases {
            let modulo = 1 << testCase.timestampBits
            // A rate the file spells as null is a rate the host does not know.
            // Swift has no such Double, so it arrives here as a NaN - which is
            // exactly the shape an unknown rate takes in a real host.
            let rate = testCase.samplingRateHz ?? Double.nan
            let got = TimestampUnwrap.reorderWindowTicks(samplingRateHz: rate, maxTicks: modulo)
            XCTAssertEqual(got, testCase.expectedReorderWindowTicks,
                           accuracy: max(testCase.tolerance, 1e-9),
                           "window for rate \(String(describing: testCase.samplingRateHz)) "
                           + "at \(testCase.timestampBits) bits")
        }
    }

    /// The values the shared set cannot spell.
    ///
    /// An unknown rate arriving as a division result rather than as a literal
    /// zero is the case that matters: 32768 / 0 is +Infinity in Swift, not an
    /// error, and a host that lets it through gets a window wider than the
    /// modulo. Every backward step then reads as a reorder, every roll-over is
    /// lost, and nothing looks wrong until a recording comes out 512 s short.
    func testWindowIsZeroForEveryShapeOfUnknownRate() {
        let mod = TimestampUnwrap.ticksMax3Byte
        XCTAssertEqual(TimestampUnwrap.reorderWindowTicks(samplingRateHz: .infinity, maxTicks: mod), 0.0)
        XCTAssertEqual(TimestampUnwrap.reorderWindowTicks(samplingRateHz: .nan, maxTicks: mod), 0.0)
        XCTAssertEqual(TimestampUnwrap.reorderWindowTicks(samplingRateHz: 0.0, maxTicks: mod), 0.0)
        XCTAssertEqual(TimestampUnwrap.reorderWindowTicks(samplingRateHz: -5.0, maxTicks: mod), 0.0)
        // The shape it actually arrives in: interpretInquiryResponseShimmer3
        // divides 32768 by the ADC value out of the packet.
        XCTAssertEqual(TimestampUnwrap.reorderWindowTicks(samplingRateHz: 32768.0 / 0.0, maxTicks: mod), 0.0)
    }

    // MARK: - TimeSensor, which is what actually runs the rule

    /// 51.2 Hz is a divider of 640 ticks, so eight sample periods is 5120.
    private let windowAt51Point2Hz = TimestampUnwrap.reorderWindowTicks(
        samplingRateHz: 51.2, maxTicks: TimestampUnwrap.ticksMax3Byte)

    private func milliseconds(_ ticks: Double) -> Double {
        return ticks / 32768.0 * 1000.0
    }

    func testTimeSensorPlacesASwappedPairWhereItWasTaken() {
        XCTAssertEqual(windowAt51Point2Hz, 5120.0)

        let sensor = TimeSensor()
        sensor.reorderWindowTicks = windowAt51Point2Hz

        // Two adjacent packets delivered the wrong way round. Each is placed
        // when it was taken, so the series dips - honestly - rather than
        // gaining a whole modulo.
        let wire = [10000.0, 11280.0, 10640.0, 11920.0]
        let got = wire.map { sensor.calibrateTimeStamp(timeStamp: $0) }
        for (i, ticks) in wire.enumerated() {
            XCTAssertEqual(got[i], milliseconds(ticks), accuracy: 1e-9, "sample \(i)")
        }
        XCTAssertEqual(sensor.CurrentTimeStampCycle, 0.0)
        XCTAssertFalse(sensor.lastRecordRejected)
    }

    /// What the reorder window buys, stated as the difference it makes.
    ///
    /// With the branch off - which is what an unknown sampling rate has to mean
    /// - the same swapped pair is read as a roll-over and the recording gains
    /// 512 seconds from that point on. This is the old behaviour, kept as a
    /// test so that the value of wiring the rate through is not theoretical.
    func testTimeSensorWithoutAWindowChargesAModuloForTheSameSwap() {
        let sensor = TimeSensor()
        sensor.reorderWindowTicks = 0.0

        _ = sensor.calibrateTimeStamp(timeStamp: 10000)
        _ = sensor.calibrateTimeStamp(timeStamp: 11280)
        let late = sensor.calibrateTimeStamp(timeStamp: 10640)

        XCTAssertEqual(late, milliseconds(10640 + Double(TimestampUnwrap.ticksMax3Byte)),
                       accuracy: 1e-9)
        XCTAssertEqual(sensor.CurrentTimeStampCycle, 1.0)
    }

    func testTimeSensorRejectsAnUnstampedRecordWithoutDisturbingTheNext() {
        let sensor = TimeSensor()
        sensor.reorderWindowTicks = windowAt51Point2Hz

        let first = sensor.calibrateTimeStamp(timeStamp: 7406506)
        XCTAssertFalse(sensor.lastRecordRejected)

        // A record the firmware never stamped. The timeline holds where it was.
        let unstamped = sensor.calibrateTimeStamp(timeStamp: 0)
        XCTAssertTrue(sensor.lastRecordRejected)
        XCTAssertEqual(unstamped, first, accuracy: 0.0)

        // And the next real sample reads as the ordinary step forward it is,
        // not as a second roll-over.
        let next = sensor.calibrateTimeStamp(timeStamp: 7406571)
        XCTAssertFalse(sensor.lastRecordRejected)
        XCTAssertEqual(next, milliseconds(7406571), accuracy: 1e-9)
        XCTAssertEqual(sensor.CurrentTimeStampCycle, 0.0)
    }

    /// A roll-over that lands exactly on zero is still a roll-over: what
    /// separates it from an unstamped record is where its predecessor was.
    func testTimeSensorStillAcceptsAGenuineRollOverOntoZero() {
        let sensor = TimeSensor()
        sensor.reorderWindowTicks = windowAt51Point2Hz

        _ = sensor.calibrateTimeStamp(timeStamp: 16777116)
        let wrapped = sensor.calibrateTimeStamp(timeStamp: 0)

        XCTAssertFalse(sensor.lastRecordRejected)
        XCTAssertEqual(wrapped, milliseconds(Double(TimestampUnwrap.ticksMax3Byte)), accuracy: 1e-9)
        XCTAssertEqual(sensor.CurrentTimeStampCycle, 1.0)
    }

    /// Forward motion is the default, so a roll-over preceded by a long dropout
    /// is still a roll-over. A rule that defaults to "corrupt" fails here.
    func testTimeSensorKeepsARollOverAfterHeavyLoss() {
        let sensor = TimeSensor()
        sensor.reorderWindowTicks = windowAt51Point2Hz

        _ = sensor.calibrateTimeStamp(timeStamp: 16000000)
        let after = sensor.calibrateTimeStamp(timeStamp: 100)

        XCTAssertEqual(after, milliseconds(Double(TimestampUnwrap.ticksMax3Byte) + 100),
                       accuracy: 1e-9)
        XCTAssertEqual(sensor.CurrentTimeStampCycle, 1.0)
    }

    /// The ObjectCluster a consumer actually reads: the sensor values survive,
    /// the time does not, and `timestampValid` is how a caller tells.
    func testUnstampedRecordIsFlaggedOnTheObjectCluster() {
        let sensor = TimeSensor()
        sensor.packetIndexTimeStamp = 0
        sensor.sensorEnabled = true
        sensor.reorderWindowTicks = windowAt51Point2Hz

        let good = sensor.processData(sensorPacket: [0xEA, 0x03, 0x71],
                                      objectCluster: ObjectCluster(deviceName: "test"))
        XCTAssertTrue(good.timestampValid)

        let unstamped = sensor.processData(sensorPacket: [0x00, 0x00, 0x00],
                                           objectCluster: ObjectCluster(deviceName: "test"))
        XCTAssertFalse(unstamped.timestampValid)
        // The raw field is still reported as the packet sent it.
        let rawIndex = unstamped.SignalNames.firstIndex {
            $0.contains(Sensor.SensorFormats.Raw.rawValue)
        }
        XCTAssertNotNil(rawIndex)
        XCTAssertEqual(unstamped.SignalData[rawIndex!], 0.0)
    }
}
